# payra-sdk-python/example_signature.py

import time
from payra_sdk import PayraSignature, PayraSDKException, PayraUtils

# --- Example Payment Data (as received from frontend) ---
# This data should come directly from your frontend, with `amount_wei` already in wei/smallest units.
PAYMENT_DATA = {
    "network": "polygon",
    "token_address": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F", # Example ERC20 Token Address
    "order_id": "ORDER-1760273788561-93-661",
    "amount_wei": 12340000, # wei/smallest units (e.g., 2 * 10^6 for a token with 6 decimals)
    "timestamp": 1760274141, # Unix timestamp (seconds)
    "payer_address": "0xbCd665bE1393094bfD5013E0e2e21aB6Df1D6078"
}

def run_example():

    print("\nPayment Data received from frontend:")
    for key, value in PAYMENT_DATA.items():
        print(f" {key}: {value}")

    try:
        #Convert USD/token to Wei if you need
        #amount_wei = PayraUtils.to_wei(3.34, 'polygon', 'usdt')

        # Initialize the signature generator with the backend's private key
        payra_signature = PayraSignature()

        # Generate the signature
        print("\nGenerating signature...")
        signature = payra_signature.generate(
            network=PAYMENT_DATA["network"],
            token_address=PAYMENT_DATA["token_address"],
            order_id=PAYMENT_DATA["order_id"],
            amount_wei=PAYMENT_DATA["amount_wei"],
            timestamp=PAYMENT_DATA["timestamp"],
            payer_address=PAYMENT_DATA["payer_address"],
        )

        print(f"\nSignature generated successfully:")
        print(f"  Signature: {signature}")
        print("\nThis signature should match the one generated by your JS frontend (if it were signing with this private key).")
        print("This is the signature you will send back to the frontend for the `payOrder` contract call.")

        # --- Optional: Verify the signature locally ---
        # This demonstrates how the backend could verify if needed (e.g., if signature came from other source)
        # It should recover the address that matches the private key used for signing.
        print("\n--- Verifying signature locally (optional) ---")
        recovered_address = payra_signature.verify(
            network=PAYMENT_DATA["network"],
            token_address=PAYMENT_DATA["token_address"],
            order_id=PAYMENT_DATA["order_id"],
            amount_wei=PAYMENT_DATA["amount_wei"],
            timestamp=PAYMENT_DATA["timestamp"],
            payer_address=PAYMENT_DATA["payer_address"],
            signature=signature
        )
        print(f"Recovered address from signature: {recovered_address}")

        local_address = payra_signature.get_account_address(PAYMENT_DATA["network"])

        if recovered_address.lower() == local_address.lower():
            print("Local verification successful: Recovered address matches the signer's address.")
        else:
            print("Local verification FAILED: Recovered address does NOT match the signer's address.")

    except PayraSDKException as e:
        print(f"\nAn error occurred with Payra SDK: {e}")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")

if __name__ == "__main__":
    from eth_account import Account # Needed for example's signer address print
    run_example()
